site_name: Chroodle
site_url: https://ugecko.github.io/chroodleWeb/
theme:
  language: en
  logo: assets/chroodle.png
  features:
    - content.code.select
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  name: material
  font:
    text: Fauna One
    code: JetBrains Mono
  icon:
    annotation: material/help-circle
  palette:
    scheme: slate
    primary: custom
    accent: custom

plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Learn:
    - Creating Environments : learn/envs.md
    - Fog : learn/fog.md
    - Geometry : learn/geometry.md
    - Runtime Unity Editor : learn/rue.md
  - Data:
    - Chroma Logs : data/clogs.md
    - Environment Data : data/envdata.md
    - Geometry Ref. Table : data/geotable.md
  - Other:
    - Error Troubleshooting : other/etroubleshoot.md
    - Contribute : other/contribute.md

extra_javascript:
  - js/extra.js
extra_css:
  - stylesheets/extra.css

copyright: ❤️ Handcrafted with love by the BeatSaber community ❤️